#
# !!! DO NOT EDIT THIS FILE !!!
#
# Unless you are adding new features to start_scripts or trying to
# figure out why something is not working, do not edit this file.
#
# Any changes you need to do to use start_scripts should be made in
# the file ..\..\psxhacks-start-override.ps1, i.e
# psxhacks-start-override.ps1 two directory levels above this
# directory - in the same directory as the psxhacks directory is placed.
#
# !!! DO NOT EDIT THIS FILE !!!

# Note: EVERYONE will need an override file of some sort. Maybe you
# don't have thermal printer, maybe you use frankenusb, maybe not, ...

# Shared helper functions (Show-ErrorAndExit, KillProcess, etc.) — see functions.ps1.
. "$PSScriptRoot\functions.ps1"

# Location of the override file — sim-specific settings live here,
# outside the git tree. Change this path in-place if your layout
# differs. Resolved via GetFullPath (not Resolve-Path, which requires the
# path to exist) so ".." segments are collapsed before the path is ever
# shown to the user - a raw "..\.." is confusing to someone unfamiliar
# with relative paths.
$OverrideFile = [System.IO.Path]::GetFullPath("$PSScriptRoot\..\..\psxhacks-start-override.ps1")
if (-not (Test-Path $OverrideFile)) {
    Show-ErrorAndExit "Override file not found: $OverrideFile`nCopy start_scripts\psxhacks-start-override-EXAMPLE.ps1 to $OverrideFile and edit it."
}

# Location of the current flavor file — updated by configure_flavor.ps1.
# Defaults to the same directory as the override file.
$FlavorFile = [System.IO.Path]::GetFullPath("$PSScriptRoot\..\..\psxhacks-current-flavor.ps1")
# $IsConfiguringFlavor is set by configure_flavor.ps1 itself before it dot-
# sources this file - telling the user to "run configure_flavor.ps1" would
# be nonsensical while that's exactly the script currently running.
if (-not (Test-Path $FlavorFile) -and -not $IsConfiguringFlavor) {
    Show-WarningAndContinue "Flavor file not found: $FlavorFile`nRun configure_flavor.ps1 once to create it."
}

# Directory the psxhacks Git checkout is installed in (start_scripts is
# always a direct subdirectory of it).
$PsxhacksDevel = Split-Path $PSScriptRoot -Parent

# Directory one level above the psxhacks checkout — where the override
# file and flavor file live, outside the Git tree.
$SimBase       = Split-Path $PsxhacksDevel -Parent

# Name of the .pref file used to start the PSX main server (start_psx_main_server.ps1).
# This one ships with AerowinxStart and is the same for everyone, so unlike
# $AerowinxDir/$AerowinxPrefFiles below it has a sensible default and does
# not need to be set in the override file.
#
# This preferences file should be configured to:
#   - be a main server
#   - listen on the port defined as upstream in the master frankenrouter
#     config file (recommended: 20747) - set "Port10747=20747" in the
#     preferences file to do this
#   - not use audio
#   - not use USB controls
#   - have a very small window (uses less graphics resources this way)
#     that can be minimized
$AerowinxMainServerPrefFile = "main-server.pref"

# Which radio/voice app to start. Override in the override file if needed.
$RadioApp           = "vPilot"

#  Where the EFB config file is located (the EFB controls this and
#  expect the file to be in this location, so don't override this)
$PsxNetEfbConfigDir = "$env:USERPROFILE\Documents\PSX.NET.EFB"

# Flavor-derived variables — overridden at runtime by psxhacks-current-flavor.ps1.
# These defaults apply when configure_flavor.ps1 has not yet been run.
$AirlineIcao    = "BAW"
$AirlineIata    = "BA"
$SimfestEmail   = ""
$PsxSoundsRb211 = "66"
$VpilotPlugin   = "none"

# Reset to empty every run (rather than leaving it undefined): if you run
# more than one script in the same PowerShell session/console, a leftover
# $HoppieLogonCode from a previous script's dot-sourced common.ps1 (which
# loads the flavor file at its very end, possibly setting this) would
# otherwise still be in scope here and get mistaken by the check below for
# "set directly in the override file this run".
$HoppieLogonCode = ""

# Your Hoppie logon code(s) - has no default in common.ps1. You must set
# $HoppieLogonCodes (a hashtable) in the override file - configure_flavor.ps1
# will let you pick one by name (even if it only has one entry) and will
# set $HoppieLogonCode for you:
#   $HoppieLogonCodes = @{ "normal" = "yourcode1"; "testing" = "yourcode2" }
# Setting $HoppieLogonCode directly in the override file instead (legacy
# style) still works, but prints a startup warning recommending
# $HoppieLogonCodes instead. See the check below.

# Your Simfest Portal email address(es). The recommended way to set this is
# a named hashtable in the override file - configure_flavor.ps1 will let
# you pick one by name (even if it only has one entry) and will set
# $SimfestEmail for you:
#   $SimfestEmails = @{ "work" = "work@example.com"; "personal" = "me@gmail.com" }
# Setting $SimfestEmail directly in the override file still works, but is
# checked for below and prints a startup warning recommending
# $SimfestEmails instead.

# Directory for frankenusb's config file (frankenusb.conf by default - see
# the startup check below). This is a working directory you create
# yourself, not an installer target, so a generic default is fine here.
$FrankenusbDir      = "$SimBase\frankenusb"

# Options for the routers
#
# Directory for frankenrouter's config file(s) (one for master, one for
# slave, if you run both). This is a working directory you create
# yourself, not an installer target, so a generic default is fine here.
# See the startup check below for what's required in it.
$FrankenrouterDir           = "$SimBase\frankenrouter"
# $FrankenrouterMasterOptions/$FrankenrouterSlaveOptions have no default
# --config-file here since the config file name is yours to choose (see
# psxhacks-start-override-EXAMPLE.ps1 for an example using
# frankensim-master.toml/frankensim-slave.toml).
$FrankenrouterMasterOptions = @()
$FrankenrouterSlaveOptions  = @()
# These must match the port number configured in the corresponding TOML
# config file (see $FrankenrouterMasterOptions/$FrankenrouterSlaveOptions
# above) - frankenrouter itself doesn't read the port from here, these are
# only used by other scripts/addons that need to know where to connect.
$FrankenrouterSlavePort     = 10747
$FrankenrouterMasterPort    = 10748
# Location of router web interface
$FrankenrouterSlaveWeb      = "http://localhost:8747"

# Options for the rest of the frankenaddons, e.g a config file name
#
# If port 10748 is used it is because those usually run in the master
# sim, and my master sim is on port 10748
#
# $ExampleOptions = @("--foo", "--bar=123")
$FrankenweatherOptions = @()
$FrankentankerOptions  = @()
$FrankenusbOptions  = @()
$FrankenwindOptions  = @()
$FrankenidentOptions = @()
$FrankencduproxyOptions = @()
$FrankenmsfsbridgeOptions = @()
$FrankenprintOptions = @()
$FrankenpushOptions  = @()

# Per-addon alternative psxhacks repo directory name.
# Set to the name of a sibling directory to run that addon from a different
# checkout of the psxhacks repo.  Leave $null to use $PsxhacksDevel.
# All of these should normally be $null - only set one when you are
# testing a different (e.g. in-development) version of that specific
# addon; everyone else should leave the whole repo group alone.
# Example: $FrankenusbRepo = "psxhacks-frankenusb-devel"
#   -> runs C:\fs\psxhacks-frankenusb-devel\frankenusb.py
$FrankencduproxyRepo    = $null
$FrankenweatherRepo     = $null
$FrankenidentRepo       = $null
$FrankenrouterRepo      = $null
$FrankentankerRepo      = $null
$FrankenusbRepo         = $null
$FrankenwindRepo        = $null
$FrankenmsfsbridgeRepo  = $null
$FrankenprintRepo       = $null
$FrankenpushRepo        = $null

# Which of the addons that we can manage you actually want started in
# your sim. You can override these in the override file.

#
# Addons that run in the master sim (if enabled)
#

$StartFrankenweather     = $false
$StartFrankenmsfsbridge  = $false
$StartFrankentanker  = $false
$StartFrankenusb    = $false
$StartFrankenident  = $false
$StartPsxSounds     = $false
$StartVpilot        = $false
$StartPsxNetVatsim  = $false
$StartAcarsPrint    = $false
$StartFrankenprint  = $false
$StartFrankenpush   = $false
$StartEfb           = $false
$StartSimObjectRouter    = $false

$StartPsxNetMsfsClient   = $false
$StartPsxNetMsfsRouter   = $false
$StartPsxNetWeatherRadar = $false
$StartPsxNetGroundCrew   = $false

$StartFrankencduproxy = $false
$StartCsCdu           = $false

$StartSrslPsxMaster = $false
$StartSrslPsxSlave  = $false

#
# Addons that run in the master sim (if enabled)
#
$StartBacars        = $false
$StartPsxNet        = $false
$StartCpdlc         = $false


# Set to $true in the override file to enable apply_window_positions.ps1
$ChangeWindowPositions = $false

# Set to $false in the override file to skip the interactive pauses in startsim_slave.ps1
$StopAfterSlaveRouterStart = $true
$StopBeforeMsfsStart       = $true

# Retry interval and timeout (seconds) used by apply_window_positions.ps1 when
# waiting for an addon window to appear after the addon is started.
$WindowPositionInitialDelay    = 2
$WindowPositionSleepSeconds    = 0.5
$WindowPositionSleepSecondsMax = 5

# Human-readable display names for each sim addon key used in window-positioning scripts
$SimAddonNames = [ordered]@{
    "BACARS"               = "BACARS"
    "PSX.NET.MSFS"         = "PSX.NET MSFS Client"
    "PSX.NET.MSFS.Router"  = "PSX.NET MSFS Router"
    "PSX.NET"              = "PSX.NET"
    "PSXSounds"            = "PSX Sounds"
    "HAFAP/CPDLC"          = "HAFAP/CPDLC"
    "vPilot"               = "vPilot"
    "PSX.NET.VATSIM"       = "PSX.NET.VATSIM"
    "PSX.NET.EFB"          = "PSX.NET EFB"
    "ACARS Print App"      = "ACARS Print App"
    "frankenusb"           = "FrankenUSB"
    "frankenweather"       = "FrankenWeather"
    "frankentanker"        = "FrankenTanker"
    "frankenident"         = "FrankenIDENT"
    "frankencduproxy"      = "FrankenCDU Proxy"
    "frankenmsfsbridge"    = "FrankenMSFSBridge"
    "frankenprint"         = "FrankenPrinter"
    "frankenpush"          = "FrankenPush"
    "frankenrouter slave"    = "FrankenRouter (slave)"
    "frankenrouter master"   = "FrankenRouter (master)"
    "PSX.NET.WeatherRadar"   = "PSX.NET WeatherRadar"
    "PSX.NET.GroundCrew"     = "PSX.NET GroundCrew"
    "SimObjectRouter"        = "SimObjectRouter"
    "SRSL-PSX master"        = "SRSL-PSX (master)"
    "SRSL-PSX slave"         = "SRSL-PSX (slave)"
}


# Apps launched as-is during sim startup (no custom start script
# needed).  Override $NonscriptedApps in the override file to replace
# this list entirely.
$NonscriptedApps = @()

# $OverrideFile's existence was already verified above (Show-ErrorAndExit
# if missing), so it is safe to dot-source unconditionally here.
. $OverrideFile

# $HoppieLogonCode resets to "" above (not a real value) - you must set
# $HoppieLogonCodes (a hashtable) in the override file, unless you set the
# legacy singular $HoppieLogonCode directly instead (still works, but
# warns - checked here, before the flavor file below may set
# $HoppieLogonCode itself as configure_flavor.ps1's resolved pick). Only
# needed at all if you actually run BACARS or HAFAP/CPDLC.
if ($StartBacars -or $StartCpdlc) {
    if (-not [string]::IsNullOrWhiteSpace($HoppieLogonCode)) {
        Show-WarningAndContinue "`$HoppieLogonCode is set directly in $OverrideFile.`nThis still works, but the recommended approach is to define `$HoppieLogonCodes (a hashtable) instead and let configure_flavor.ps1 pick from it. See psxhacks-start-override-EXAMPLE.ps1."
    } elseif (-not ($HoppieLogonCodes -is [hashtable] -and $HoppieLogonCodes.Count -gt 0)) {
        Show-ErrorAndExit "`$HoppieLogonCodes is not set.`nEdit $OverrideFile and set `$HoppieLogonCodes (a hashtable) to your Hoppie logon code(s), or set the legacy `$HoppieLogonCode directly. See psxhacks-start-override-EXAMPLE.ps1."
    }
}

# $SimfestEmail/$SimfestEmails have no such requirement - Simfest email is
# optional (unlike the Hoppie logon code, which BACARS/HAFAP need to
# function at all).
if ($SimfestEmail -ne "") {
    Show-WarningAndContinue "`$SimfestEmail is set directly in $OverrideFile.`nThis still works, but the recommended approach is to define `$SimfestEmails (a hashtable) instead and let configure_flavor.ps1 pick from it. See psxhacks-start-override-EXAMPLE.ps1."
}

# $PsxhacksPython has no default - it must be set in the override file
# (see psxhacks-start-override-EXAMPLE.ps1) and point at a real python.exe.
if ([string]::IsNullOrWhiteSpace($PsxhacksPython)) {
    Show-ErrorAndExit "`$PsxhacksPython is not set.`nEdit $OverrideFile and set `$PsxhacksPython to the path of python.exe in your Python virtual environment."
} elseif (-not (Test-Path $PsxhacksPython -PathType Leaf)) {
    Show-ErrorAndExit "`$PsxhacksPython not found: $PsxhacksPython`nEdit $OverrideFile and set `$PsxhacksPython to the path of python.exe in your Python virtual environment."
} elseif ([System.IO.Path]::GetExtension($PsxhacksPython) -ne ".exe") {
    Show-ErrorAndExit "`$PsxhacksPython is not an .exe file: $PsxhacksPython`nEdit $OverrideFile and set `$PsxhacksPython to the path of python.exe in your Python virtual environment."
} elseif (-not (Test-Path (Join-Path (Split-Path $PsxhacksPython -Parent) "activate"))) {
    Show-ErrorAndExit "`$PsxhacksPython does not look like it is inside a Python virtual environment (no 'activate' next to it): $PsxhacksPython`nEdit $OverrideFile and set `$PsxhacksPython to the path of python.exe in your Python virtual environment."
}

# $AerowinxDir has no default - it must be set in the override file (see
# psxhacks-start-override-EXAMPLE.ps1) and point at a real Aerowinx PSX
# install. Unlike the addons below, PSX itself is always started (both
# start_psx_main_server.ps1 on the master and start_psx_main_clients.ps1 on
# the slave), so this check is unconditional.
if ([string]::IsNullOrWhiteSpace($AerowinxDir)) {
    Show-ErrorAndExit "`$AerowinxDir is not set.`nEdit $OverrideFile and set `$AerowinxDir to your Aerowinx PSX installation directory."
} elseif (-not (Test-Path $AerowinxDir -PathType Container)) {
    Show-ErrorAndExit "`$AerowinxDir not found: $AerowinxDir`nEdit $OverrideFile and set `$AerowinxDir to your Aerowinx PSX installation directory."
} elseif (-not (Test-Path (Join-Path $AerowinxDir "AerowinxStart.jar"))) {
    Show-ErrorAndExit "`$AerowinxDir does not look like an Aerowinx PSX installation (no AerowinxStart.jar found): $AerowinxDir`nEdit $OverrideFile and set `$AerowinxDir to your Aerowinx PSX installation directory."
}

# $AerowinxPrefFiles has no default - it must be set in the override file
# (see psxhacks-start-override-EXAMPLE.ps1) to the list of .pref files for
# the PSX main client instances to start in the slave sim
# (start_psx_main_clients.ps1). Unconditional for the same reason as $AerowinxDir
# above.
if (-not $AerowinxPrefFiles -or $AerowinxPrefFiles.Count -eq 0) {
    Show-ErrorAndExit "`$AerowinxPrefFiles is not set.`nEdit $OverrideFile and set `$AerowinxPrefFiles to the list of .pref files for your PSX main client instances."
}

# $BacarsDir has no default - it must be set in the override file (see
# psxhacks-start-override-EXAMPLE.ps1) and point at a real BACARS install,
# but only if BACARS is actually enabled. We will add the same kind of
# check for the other addons later.
if ($StartBacars) {
    if ([string]::IsNullOrWhiteSpace($BacarsDir)) {
        Show-ErrorAndExit "`$StartBacars is `$true but `$BacarsDir is not set.`nEdit $OverrideFile and set `$BacarsDir to your BACARS installation directory."
    } elseif (-not (Test-Path $BacarsDir -PathType Container)) {
        Show-ErrorAndExit "`$BacarsDir not found: $BacarsDir`nEdit $OverrideFile and set `$BacarsDir to your BACARS installation directory."
    } elseif (-not (Test-Path (Join-Path $BacarsDir "PSX.Bacars.UI.exe"))) {
        Show-ErrorAndExit "`$BacarsDir does not look like a BACARS installation (no PSX.Bacars.UI.exe found): $BacarsDir`nEdit $OverrideFile and set `$BacarsDir to your BACARS installation directory."
    }
}

# $PsxNetDir has no default - it must be set in the override file (see
# psxhacks-start-override-EXAMPLE.ps1) and point at a real PSX.NET install,
# but only if PSX.NET is actually enabled.
if ($StartPsxNet) {
    if ([string]::IsNullOrWhiteSpace($PsxNetDir)) {
        Show-ErrorAndExit "`$StartPsxNet is `$true but `$PsxNetDir is not set.`nEdit $OverrideFile and set `$PsxNetDir to your PSX.NET installation directory."
    } elseif (-not (Test-Path $PsxNetDir -PathType Container)) {
        Show-ErrorAndExit "`$PsxNetDir not found: $PsxNetDir`nEdit $OverrideFile and set `$PsxNetDir to your PSX.NET installation directory."
    } elseif (-not (Test-Path (Join-Path $PsxNetDir "PSX.NET.exe"))) {
        Show-ErrorAndExit "`$PsxNetDir does not look like a PSX.NET installation (no PSX.NET.exe found): $PsxNetDir`nEdit $OverrideFile and set `$PsxNetDir to your PSX.NET installation directory."
    }
}

# $PsxNetVatsimDir has no default - it must be set in the override file (see
# psxhacks-start-override-EXAMPLE.ps1) and point at a real PSX.NET.VATSIM
# install, but only if PSX.NET.VATSIM is actually enabled.
if ($StartPsxNetVatsim) {
    if ([string]::IsNullOrWhiteSpace($PsxNetVatsimDir)) {
        Show-ErrorAndExit "`$StartPsxNetVatsim is `$true but `$PsxNetVatsimDir is not set.`nEdit $OverrideFile and set `$PsxNetVatsimDir to your PSX.NET.VATSIM installation directory."
    } elseif (-not (Test-Path $PsxNetVatsimDir -PathType Container)) {
        Show-ErrorAndExit "`$PsxNetVatsimDir not found: $PsxNetVatsimDir`nEdit $OverrideFile and set `$PsxNetVatsimDir to your PSX.NET.VATSIM installation directory."
    } elseif (-not (Test-Path (Join-Path $PsxNetVatsimDir "GeoVR.PSX.Client.Wpf.exe"))) {
        Show-ErrorAndExit "`$PsxNetVatsimDir does not look like a PSX.NET.VATSIM installation (no GeoVR.PSX.Client.Wpf.exe found): $PsxNetVatsimDir`nEdit $OverrideFile and set `$PsxNetVatsimDir to your PSX.NET.VATSIM installation directory."
    }
}

# $PsxNetMsfsClientDir has no default - it must be set in the override file
# (see psxhacks-start-override-EXAMPLE.ps1) and point at a real PSX.NET.MSFS
# Client install, but only if PSX.NET.MSFS.Client is actually enabled.
if ($StartPsxNetMsfsClient) {
    if ([string]::IsNullOrWhiteSpace($PsxNetMsfsClientDir)) {
        Show-ErrorAndExit "`$StartPsxNetMsfsClient is `$true but `$PsxNetMsfsClientDir is not set.`nEdit $OverrideFile and set `$PsxNetMsfsClientDir to your PSX.NET.MSFS.Client installation directory."
    } elseif (-not (Test-Path $PsxNetMsfsClientDir -PathType Container)) {
        Show-ErrorAndExit "`$PsxNetMsfsClientDir not found: $PsxNetMsfsClientDir`nEdit $OverrideFile and set `$PsxNetMsfsClientDir to your PSX.NET.MSFS.Client installation directory."
    } elseif (-not (Test-Path (Join-Path $PsxNetMsfsClientDir "PSX.NET.MSFS2024.Client.exe"))) {
        Show-ErrorAndExit "`$PsxNetMsfsClientDir does not look like a PSX.NET.MSFS.Client installation (no PSX.NET.MSFS2024.Client.exe found): $PsxNetMsfsClientDir`nEdit $OverrideFile and set `$PsxNetMsfsClientDir to your PSX.NET.MSFS.Client installation directory."
    }
}

# $PsxNetMsfsRouterDir has no default - it must be set in the override file
# (see psxhacks-start-override-EXAMPLE.ps1) and point at a real PSX.NET.MSFS
# Router install, but only if PSX.NET.MSFS.Router is actually enabled.
if ($StartPsxNetMsfsRouter) {
    if ([string]::IsNullOrWhiteSpace($PsxNetMsfsRouterDir)) {
        Show-ErrorAndExit "`$StartPsxNetMsfsRouter is `$true but `$PsxNetMsfsRouterDir is not set.`nEdit $OverrideFile and set `$PsxNetMsfsRouterDir to your PSX.NET.MSFS.Router installation directory."
    } elseif (-not (Test-Path $PsxNetMsfsRouterDir -PathType Container)) {
        Show-ErrorAndExit "`$PsxNetMsfsRouterDir not found: $PsxNetMsfsRouterDir`nEdit $OverrideFile and set `$PsxNetMsfsRouterDir to your PSX.NET.MSFS.Router installation directory."
    } elseif (-not (Test-Path (Join-Path $PsxNetMsfsRouterDir "PSX.NET.MSFS.Router.exe"))) {
        Show-ErrorAndExit "`$PsxNetMsfsRouterDir does not look like a PSX.NET.MSFS.Router installation (no PSX.NET.MSFS.Router.exe found): $PsxNetMsfsRouterDir`nEdit $OverrideFile and set `$PsxNetMsfsRouterDir to your PSX.NET.MSFS.Router installation directory."
    }
}

# $PsxNetWeatherRadarDir has no default - it must be set in the override file
# (see psxhacks-start-override-EXAMPLE.ps1) and point at a real
# PSX.NET.WeatherRadar install, but only if PSX.NET.WeatherRadar is actually
# enabled.
if ($StartPsxNetWeatherRadar) {
    if ([string]::IsNullOrWhiteSpace($PsxNetWeatherRadarDir)) {
        Show-ErrorAndExit "`$StartPsxNetWeatherRadar is `$true but `$PsxNetWeatherRadarDir is not set.`nEdit $OverrideFile and set `$PsxNetWeatherRadarDir to your PSX.NET.WeatherRadar installation directory."
    } elseif (-not (Test-Path $PsxNetWeatherRadarDir -PathType Container)) {
        Show-ErrorAndExit "`$PsxNetWeatherRadarDir not found: $PsxNetWeatherRadarDir`nEdit $OverrideFile and set `$PsxNetWeatherRadarDir to your PSX.NET.WeatherRadar installation directory."
    } elseif (-not (Test-Path (Join-Path $PsxNetWeatherRadarDir "PSX.NET.WeatherRadar.exe"))) {
        Show-ErrorAndExit "`$PsxNetWeatherRadarDir does not look like a PSX.NET.WeatherRadar installation (no PSX.NET.WeatherRadar.exe found): $PsxNetWeatherRadarDir`nEdit $OverrideFile and set `$PsxNetWeatherRadarDir to your PSX.NET.WeatherRadar installation directory."
    }
}

# $PsxNetGroundCrewDir has no default - it must be set in the override file
# (see psxhacks-start-override-EXAMPLE.ps1) and point at a real
# PSX.NET.GroundCrew install, but only if PSX.NET.GroundCrew is actually
# enabled.
if ($StartPsxNetGroundCrew) {
    if ([string]::IsNullOrWhiteSpace($PsxNetGroundCrewDir)) {
        Show-ErrorAndExit "`$StartPsxNetGroundCrew is `$true but `$PsxNetGroundCrewDir is not set.`nEdit $OverrideFile and set `$PsxNetGroundCrewDir to your PSX.NET.GroundCrew installation directory."
    } elseif (-not (Test-Path $PsxNetGroundCrewDir -PathType Container)) {
        Show-ErrorAndExit "`$PsxNetGroundCrewDir not found: $PsxNetGroundCrewDir`nEdit $OverrideFile and set `$PsxNetGroundCrewDir to your PSX.NET.GroundCrew installation directory."
    } elseif (-not (Test-Path (Join-Path $PsxNetGroundCrewDir "PSX.NET.GroundCrew.exe"))) {
        Show-ErrorAndExit "`$PsxNetGroundCrewDir does not look like a PSX.NET.GroundCrew installation (no PSX.NET.GroundCrew.exe found): $PsxNetGroundCrewDir`nEdit $OverrideFile and set `$PsxNetGroundCrewDir to your PSX.NET.GroundCrew installation directory."
    }
}

# $PsxNetEfbDir has no default - it must be set in the override file (see
# psxhacks-start-override-EXAMPLE.ps1) and point at a real PSX.NET.EFB
# install, but only if PSX.NET.EFB is actually enabled.
if ($StartEfb) {
    if ([string]::IsNullOrWhiteSpace($PsxNetEfbDir)) {
        Show-ErrorAndExit "`$StartEfb is `$true but `$PsxNetEfbDir is not set.`nEdit $OverrideFile and set `$PsxNetEfbDir to your PSX.NET.EFB installation directory."
    } elseif (-not (Test-Path $PsxNetEfbDir -PathType Container)) {
        Show-ErrorAndExit "`$PsxNetEfbDir not found: $PsxNetEfbDir`nEdit $OverrideFile and set `$PsxNetEfbDir to your PSX.NET.EFB installation directory."
    } elseif (-not (Test-Path (Join-Path $PsxNetEfbDir "PSX.NET.EFB.Windows.exe"))) {
        Show-ErrorAndExit "`$PsxNetEfbDir does not look like a PSX.NET.EFB installation (no PSX.NET.EFB.Windows.exe found): $PsxNetEfbDir`nEdit $OverrideFile and set `$PsxNetEfbDir to your PSX.NET.EFB installation directory."
    }
}

# $PsxSoundsDir has no default - it must be set in the override file (see
# psxhacks-start-override-EXAMPLE.ps1) and point at a real PSXSounds
# install, but only if PSXSounds is actually enabled.
if ($StartPsxSounds) {
    if ([string]::IsNullOrWhiteSpace($PsxSoundsDir)) {
        Show-ErrorAndExit "`$StartPsxSounds is `$true but `$PsxSoundsDir is not set.`nEdit $OverrideFile and set `$PsxSoundsDir to your PSXSounds installation directory."
    } elseif (-not (Test-Path $PsxSoundsDir -PathType Container)) {
        Show-ErrorAndExit "`$PsxSoundsDir not found: $PsxSoundsDir`nEdit $OverrideFile and set `$PsxSoundsDir to your PSXSounds installation directory."
    } elseif (-not (Test-Path (Join-Path $PsxSoundsDir "PSXSounds.exe"))) {
        Show-ErrorAndExit "`$PsxSoundsDir does not look like a PSXSounds installation (no PSXSounds.exe found): $PsxSoundsDir`nEdit $OverrideFile and set `$PsxSoundsDir to your PSXSounds installation directory."
    }
}

# $CpdlcDir has no default - it must be set in the override file (see
# psxhacks-start-override-EXAMPLE.ps1) and point at a real HAFAP/CPDLC
# install, but only if HAFAP/CPDLC is actually enabled.
if ($StartCpdlc) {
    if ([string]::IsNullOrWhiteSpace($CpdlcDir)) {
        Show-ErrorAndExit "`$StartCpdlc is `$true but `$CpdlcDir is not set.`nEdit $OverrideFile and set `$CpdlcDir to your HAFAP/CPDLC installation directory."
    } elseif (-not (Test-Path $CpdlcDir -PathType Container)) {
        Show-ErrorAndExit "`$CpdlcDir not found: $CpdlcDir`nEdit $OverrideFile and set `$CpdlcDir to your HAFAP/CPDLC installation directory."
    } elseif (-not (Test-Path (Join-Path $CpdlcDir "psx-acars.py"))) {
        Show-ErrorAndExit "`$CpdlcDir does not look like a HAFAP/CPDLC installation (no psx-acars.py found): $CpdlcDir`nEdit $OverrideFile and set `$CpdlcDir to your HAFAP/CPDLC installation directory."
    }
}

# $VPilotDir has no default - it must be set in the override file (see
# psxhacks-start-override-EXAMPLE.ps1) and point at a real vPilot install,
# but only if vPilot is actually enabled.
if ($StartVpilot) {
    if ([string]::IsNullOrWhiteSpace($VPilotDir)) {
        Show-ErrorAndExit "`$StartVpilot is `$true but `$VPilotDir is not set.`nEdit $OverrideFile and set `$VPilotDir to your vPilot installation directory."
    } elseif (-not (Test-Path $VPilotDir -PathType Container)) {
        Show-ErrorAndExit "`$VPilotDir not found: $VPilotDir`nEdit $OverrideFile and set `$VPilotDir to your vPilot installation directory."
    } elseif (-not (Test-Path (Join-Path $VPilotDir "vPilot.exe"))) {
        Show-ErrorAndExit "`$VPilotDir does not look like a vPilot installation (no vPilot.exe found): $VPilotDir`nEdit $OverrideFile and set `$VPilotDir to your vPilot installation directory."
    }
}

# $AcarsPrintDir has no default - it must be set in the override file (see
# psxhacks-start-override-EXAMPLE.ps1) and point at a real ACARS Print
# install, but only if ACARS Print is actually enabled.
if ($StartAcarsPrint) {
    if ([string]::IsNullOrWhiteSpace($AcarsPrintDir)) {
        Show-ErrorAndExit "`$StartAcarsPrint is `$true but `$AcarsPrintDir is not set.`nEdit $OverrideFile and set `$AcarsPrintDir to your ACARS Print installation directory."
    } elseif (-not (Test-Path $AcarsPrintDir -PathType Container)) {
        Show-ErrorAndExit "`$AcarsPrintDir not found: $AcarsPrintDir`nEdit $OverrideFile and set `$AcarsPrintDir to your ACARS Print installation directory."
    } elseif (-not (Test-Path (Join-Path $AcarsPrintDir "AcarsPrint.jar"))) {
        Show-ErrorAndExit "`$AcarsPrintDir does not look like an ACARS Print installation (no AcarsPrint.jar found): $AcarsPrintDir`nEdit $OverrideFile and set `$AcarsPrintDir to your ACARS Print installation directory."
    }
}

# $SrslPsxMasterDir has no default - it must be set in the override file
# (see psxhacks-start-override-EXAMPLE.ps1) and point at a real SRSL-PSX
# install, but only if SRSL-PSX (master) is actually enabled. Master and
# slave use separate directories since they connect to different PSX
# instances.
if ($StartSrslPsxMaster) {
    if ([string]::IsNullOrWhiteSpace($SrslPsxMasterDir)) {
        Show-ErrorAndExit "`$StartSrslPsxMaster is `$true but `$SrslPsxMasterDir is not set.`nEdit $OverrideFile and set `$SrslPsxMasterDir to your SRSL-PSX (master) installation directory."
    } elseif (-not (Test-Path $SrslPsxMasterDir -PathType Container)) {
        Show-ErrorAndExit "`$SrslPsxMasterDir not found: $SrslPsxMasterDir`nEdit $OverrideFile and set `$SrslPsxMasterDir to your SRSL-PSX (master) installation directory."
    } elseif (-not (Test-Path (Join-Path $SrslPsxMasterDir "SRSL-PSX.jar"))) {
        Show-ErrorAndExit "`$SrslPsxMasterDir does not look like a SRSL-PSX installation (no SRSL-PSX.jar found): $SrslPsxMasterDir`nEdit $OverrideFile and set `$SrslPsxMasterDir to your SRSL-PSX (master) installation directory."
    }
}

# $SrslPsxSlaveDir has no default - it must be set in the override file
# (see psxhacks-start-override-EXAMPLE.ps1) and point at a real SRSL-PSX
# install, but only if SRSL-PSX (slave) is actually enabled.
if ($StartSrslPsxSlave) {
    if ([string]::IsNullOrWhiteSpace($SrslPsxSlaveDir)) {
        Show-ErrorAndExit "`$StartSrslPsxSlave is `$true but `$SrslPsxSlaveDir is not set.`nEdit $OverrideFile and set `$SrslPsxSlaveDir to your SRSL-PSX (slave) installation directory."
    } elseif (-not (Test-Path $SrslPsxSlaveDir -PathType Container)) {
        Show-ErrorAndExit "`$SrslPsxSlaveDir not found: $SrslPsxSlaveDir`nEdit $OverrideFile and set `$SrslPsxSlaveDir to your SRSL-PSX (slave) installation directory."
    } elseif (-not (Test-Path (Join-Path $SrslPsxSlaveDir "SRSL-PSX.jar"))) {
        Show-ErrorAndExit "`$SrslPsxSlaveDir does not look like a SRSL-PSX installation (no SRSL-PSX.jar found): $SrslPsxSlaveDir`nEdit $OverrideFile and set `$SrslPsxSlaveDir to your SRSL-PSX (slave) installation directory."
    }
}

# $CsCduExe has no default - it must be set in the override file (see
# psxhacks-start-override-EXAMPLE.ps1) and point at the CS CDU Bridge
# (CockpitSimulator) .exe, but only if the CS CDU bridge is actually
# enabled.
if ($StartCsCdu) {
    if ([string]::IsNullOrWhiteSpace($CsCduExe)) {
        Show-ErrorAndExit "`$StartCsCdu is `$true but `$CsCduExe is not set.`nEdit $OverrideFile and set `$CsCduExe to the path of your CS CDU Bridge (CockpitSimulator) .exe."
    } elseif (-not (Test-Path $CsCduExe -PathType Leaf)) {
        Show-ErrorAndExit "`$CsCduExe not found: $CsCduExe`nEdit $OverrideFile and set `$CsCduExe to the path of your CS CDU Bridge (CockpitSimulator) .exe."
    } elseif ([System.IO.Path]::GetExtension($CsCduExe) -ne ".exe") {
        Show-ErrorAndExit "`$CsCduExe is not an .exe file: $CsCduExe`nEdit $OverrideFile and set `$CsCduExe to the path of your CS CDU Bridge (CockpitSimulator) .exe."
    }
}

# $SimObjectRouterDir has no default - it must be set in the override file
# (see psxhacks-start-override-EXAMPLE.ps1) and point at a real
# SimObjectRouter install, but only if SimObjectRouter is actually enabled.
if ($StartSimObjectRouter) {
    if ([string]::IsNullOrWhiteSpace($SimObjectRouterDir)) {
        Show-ErrorAndExit "`$StartSimObjectRouter is `$true but `$SimObjectRouterDir is not set.`nEdit $OverrideFile and set `$SimObjectRouterDir to your SimObjectRouter installation directory."
    } elseif (-not (Test-Path $SimObjectRouterDir -PathType Container)) {
        Show-ErrorAndExit "`$SimObjectRouterDir not found: $SimObjectRouterDir`nEdit $OverrideFile and set `$SimObjectRouterDir to your SimObjectRouter installation directory."
    } elseif (-not (Test-Path (Join-Path $SimObjectRouterDir "PSX.NET.MSFS.Temporary.SimObjectRouter.exe"))) {
        Show-ErrorAndExit "`$SimObjectRouterDir does not look like a SimObjectRouter installation (no PSX.NET.MSFS.Temporary.SimObjectRouter.exe found): $SimObjectRouterDir`nEdit $OverrideFile and set `$SimObjectRouterDir to your SimObjectRouter installation directory."
    }
}

# $FrankenrouterDir is a working directory you create yourself (it holds
# frankenrouter's config file(s), not an installer output), so it keeps a
# generic default above. But unlike a fresh install, that directory won't
# exist until you create it, so we still need to check for it. Unlike the
# addons above, frankenrouter.py itself is always started (both
# start_router_master.ps1 and start_router_slave.ps1), so this check is
# unconditional.
if (-not (Test-Path $FrankenrouterDir -PathType Container)) {
    Show-ErrorAndExit "`$FrankenrouterDir not found: $FrankenrouterDir`nCreate this directory and place your frankenrouter config file(s) in it (one for the master router, one for the slave router, if you run both), then add --config-file=<name> to `$FrankenrouterMasterOptions and/or `$FrankenrouterSlaveOptions in $OverrideFile. See psxhacks-start-override-EXAMPLE.ps1 for an example."
}

# $FrankenusbDir is a working directory you create yourself (it holds
# frankenusb's config file, not an installer output), so it keeps a
# generic default above, but only needs to exist if FrankenUSB is enabled.
if ($StartFrankenusb) {
    if (-not (Test-Path $FrankenusbDir -PathType Container)) {
        Show-ErrorAndExit "`$FrankenusbDir not found: $FrankenusbDir`nCreate this directory and place your frankenusb config file in it (frankenusb.conf by default; if you use a different name, add it to `$FrankenusbOptions in $OverrideFile). See psxhacks-start-override-EXAMPLE.ps1 for an example."
    }
}

# Flavor settings override both defaults and machine-specific overrides.
if (Test-Path $FlavorFile) { . $FlavorFile }

if ($StartPsxNetVatsim) { $RadioApp = "PSX.NET.VATSIM" }
