# Shared constants and helpers for PSX start/stop scripts.
#
# I recommend that you do not edit this file. Instead create an
# override file that is placed outside the psxhacks Git tree in which
# you change the variables that are different in your sim.
#
# If you place the override file in the default location
# (psxhacks-start-override.ps1 in the directory above the psxhacks
# directory) it will be found automatically. Otherwise you will need
# to edit the line below.
#
# Note: EVERYONE will need an override file of some sort. Maybe you
# don't have thermal printer, maybe you use frankenusb, maybe not, ...

# Location of the override file — sim-specific settings live here,
# outside the git tree. Change this path in-place if your layout
# differs.
$OverrideFile = "$PSScriptRoot\..\..\psxhacks-start-override.ps1"

# Location of the current flavor file — updated by choose_flavors.ps1.
# Defaults to the same directory as the override file.
$FlavorFile = "$PSScriptRoot\..\..\psxhacks-current-flavor.ps1"

#
# DO NOT CHANGE ANYTHING BELOW THIS LINE ... unless you know you need to
#

$PsxhacksDevel = Split-Path $PSScriptRoot -Parent
$SimBase       = Split-Path $PsxhacksDevel -Parent

# The location of the python.exe we will use to start all Python parts
# of psxhacks. This will normally be python.exe in your Python virtual
# environment.
$PsxhacksPython      = "$SimBase\python\psxhacks-1\Scripts\python.exe"

# Location of SyncTrayzor (used in the Frankensim but disabled while
# the sim is running)
$SyncTrayzor         = "C:\Program Files\SyncTrayzor\synctrayzor.exe"

# Where the active version of BACARS is installed. Note: to change
# BACARS config you can use the "flavor" system to change e.g airline
# when you start the sim.
$BacarsDir           = "$SimBase\bacars\BACARS_V8.1.0"

# Location of PSX.NET.MSFS addons
$PsxNetMsfsClientDir = "$SimBase\psx_net_msfs\PSX.NET.MSFS20204.Client.20.0.0.5"
$PsxNetMsfsRouterDir = "$SimBase\psx_net_msfs\PSX.NET.MSFS.Router.20.0.0.5"

# Location of the EFB and PSX.NET
$PsxNetDir           = "$SimBase\psx_net\2026-04-11"
$PsxSoundsDir        = "$SimBase\psx_sounds\PSXSounds"

# Location of Hoppie's ACARS client For Aerowinx PSX and command line options
$CpdlcDir           = "$SimBase\hafap"
# --stealth is manadatory if you also use BACARS
# --min-interval=15 --max-interval=30 seems to be OK on VATSIM
$CpdlcOptions       = "--stealth","--min-interval=15","--max-interval=30"

# Location of PSX itself
$AerowinxDir        = "$SimBase\psx\Aerowinx"

# Location of vPilot
$VPilotDir          = "$SimBase\vPilot"

# Location of the PSX.NET.EFB install
$PsxNetEfbDir       = "$SimBase\psx_net_efb\PSX.NET.EFB-2.0.0.2-2025-11-12-2"

#  Where the EFB config file is located (the EFB controls this and
#  expect the file to be in this location, so don't override this)
$PsxNetEfbConfigDir = "$env:USERPROFILE\Documents\PSX.NET.EFB"

# Where the ACARS Print app is installed
$AcarsPrintDir      = "$SimBase\acars_print\AcarsPrintV1_1"

# Flavor-derived variables — overridden at runtime by psxhacks-current-flavor.ps1.
# These defaults apply when choose_flavors.ps1 has not yet been run.
$AirlineIcao    = "BAW"
$AirlineIata    = "BA"
$SimfestEmail   = ""
$PsxSoundsRb211 = "66"
$VpilotPlugin   = "Pushover"

# Your Hoppie logon code. Set this in the override file:
#   $HoppieLogonCode = "yourcode"
# If you have multiple codes and want to choose between them at startup,
# define a named hashtable instead and choose_flavors.ps1 will let you
# pick by name:
#   $HoppieLogonCodes = @{ "normal" = "yourcode1"; "testing" = "yourcode2" }
$HoppieLogonCode = "DUMMYLOGONCODE"

# Your Simfest Portal email address. Set this in the override file:
#   $SimfestEmail = "you@example.com"
# If you have multiple addresses and want to choose between them at startup,
# define a named hashtable instead and choose_flavors.ps1 will let you
# pick by name:
#   $SimfestEmails = @{ "work" = "work@example.com"; "personal" = "me@gmail.com" }

# Some of the psxhacks addons need a work directory to run in, where
# logs and other things are placed. In the Frankensim these are placed
# in the same directory (SimBase) where psxhacks is placed, but you
# can put them anywhere, just put the variable in your override file.
$FrankenFreezeDir   = "$SimBase\frankenfreeze"
$FrankenTankerDir   = "$SimBase\frankentanker"
$FrankenUsbDir      = "$SimBase\frankenusb"
$FrankenRouterDir   = "$SimBase\frankenrouter"
$FrankenWindDir     = "$SimBase\frankenwind"

# If you want to give custom options to frankenusb, e.g a config file name
$FrankenUsbOptions  = ""

# Options for the master sim router
$FrankenRouterMasterOptions = "--config-file=frankensim-core.toml"
$FrankenRouterSlaveOptions = "--config-file=frankensim-client.toml"
# Location of router web interface
$FrankenRouterSlaveWeb = "http://localhost:8747"

# Which of the addons that we can manage you actually want started in
# your sim. You can override these in the override file.

$StartCpdlc         = $true
$StartCsCdu         = $true
$StartFrankenfreeze = $false
$StartFrankenusb    = $true
$StartFrankentanker = $false
$StartFrankenwind   = $false
$StartIdent         = $false
$StartPsxSounds     = $true
$StartVpilot        = $true
$StartAcarsPrint    = $false
$StartEfb           = $true

$CsCduExe = "$SimBase\hw\cs_cdu\CockpitSimulator v2025.2.7.exe"


#
# Shared functions below
#


# Silently stop a process by name; does nothing if the process is not running
function KillProcess([string]$name) {
    Stop-Process -Name $name -Force -ErrorAction SilentlyContinue
}

# Apps launched as-is during sim startup (no custom start script
# needed).  Override $NonscriptedApps in the override file to replace
# this list entirely.
$NonscriptedApps = @()

function KillPythonScript([string]$scriptName) {
    Get-CimInstance Win32_Process -Filter "name LIKE 'python%.exe'" |
        Where-Object { $_.CommandLine -and $_.CommandLine -like "*$scriptName*" } |
        ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
}

function KillJavaJar([string]$jarName) {
    Get-CimInstance Win32_Process -Filter "name = 'java.exe'" |
        Where-Object { $_.CommandLine -like "*$jarName*" } |
        ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
}

function Delay([int]$seconds) {
    Write-Output "Waiting $seconds seconds..."
    Start-Sleep -Seconds $seconds
}

function start_nonscripted_apps {
    foreach ($app in $NonscriptedApps) {
        Write-Output "Starting $app..."
        Start-Process $app
    }
}

if (Test-Path $OverrideFile) { . $OverrideFile }

# Snapshot pre-flavor bool values so choose_flavors.ps1 can display
# "use default (yes/no)" labels showing what common.ps1 would apply.
$PreFlavorDefaults = @{
    StartCpdlc         = $StartCpdlc
    StartCsCdu         = $StartCsCdu
    StartFrankenfreeze = $StartFrankenfreeze
    StartFrankenusb    = $StartFrankenusb
    StartFrankentanker = $StartFrankentanker
    StartFrankenwind   = $StartFrankenwind
    StartIdent         = $StartIdent
    StartPsxSounds     = $StartPsxSounds
    StartVpilot        = $StartVpilot
    StartAcarsPrint    = $StartAcarsPrint
    StartEfb           = $StartEfb
}

# Flavor settings override both defaults and machine-specific overrides.
if (Test-Path $FlavorFile) { . $FlavorFile }
