# Shared constants and helpers for PSX start/stop scripts.
#
# I recommend that you do not edit this file. Instead create an
# override file that is placed outside the psxhacks Git tree in which
# you change the variables that are different in your sim.
#
# If you place the override file in the default location
# (psxhacks-start-override.ps1 in the directory above the psxhacks
# directory) it will be found automatically. Otherwise you will need
# to edit the line below.
#
# Note: EVERYONE will need an override file of some sort. Maybe you
# don't have thermal printer, maybe you use frankenusb, maybe not, ...

# Location of the override file — sim-specific settings live here,
# outside the git tree. Change this path in-place if your layout
# differs.
$OverrideFile = "$PSScriptRoot\..\..\psxhacks-start-override.ps1"

# Location of the current flavor file — updated by choose_flavors.ps1.
# Defaults to the same directory as the override file.
$FlavorFile = "$PSScriptRoot\..\..\psxhacks-current-flavor.ps1"

#
# DO NOT CHANGE ANYTHING BELOW THIS LINE unless you really know what
# you're doing, in most cases you should put your local settings in
# the override file instead.
#

$PsxhacksDevel = Split-Path $PSScriptRoot -Parent
$SimBase       = Split-Path $PsxhacksDevel -Parent

# The location of the python.exe we will use to start all Python parts
# of psxhacks. This will normally be python.exe in your Python virtual
# environment.
$PsxhacksPython      = "$SimBase\python\psxhacks-1\Scripts\python.exe"

# Location of SyncTrayzor (used in the Frankensim but disabled while
# the sim is running)
$SyncTrayzor         = "C:\Program Files\SyncTrayzor\synctrayzor.exe"

# Where the active version of BACARS is installed. Note: to change
# BACARS config you can use the "flavor" system to change e.g airline
# when you start the sim.
$BacarsDir           = "$SimBase\bacars\BACARS_V8.1.0"

# Location of PSX.NET.MSFS addons
$PsxNetMsfsClientDir = "$SimBase\psx_net_msfs\PSX.NET.MSFS20204.Client.20.0.0.5"
$PsxNetMsfsRouterDir = "$SimBase\psx_net_msfs\PSX.NET.MSFS.Router.20.0.0.5"

# Location of the EFB and PSX.NET
$PsxNetDir           = "$SimBase\psx_net\2026-04-11"
$PsxSoundsDir        = "$SimBase\psx_sounds\PSXSounds"

# Location of Hoppie's ACARS client For Aerowinx PSX and command line options
$CpdlcDir           = "$SimBase\hafap"
# --stealth is mandatory if you also use BACARS
# --min-interval=15 --max-interval=30 seems to be OK on VATSIM
# --no-no-comm fixes an annoying problem but you need Macroflight's patched version of HAFAP
$CpdlcOptions = "--stealth","--no-no-comm","--min-interval=15","--max-interval=30"

# Location of PSX itself
$AerowinxDir        = "$SimBase\psx\Aerowinx"
$AerowinxPrefFiles  = @("t9-main-noserver.pref", "t9-mcp.pref", "t9-pedestal.pref", "t9-fo.pref", "t9-overhead.pref")

# Location of vPilot
$VPilotDir          = "$SimBase\vPilot"

# Location of the PSX.NET.EFB install
$PsxNetEfbDir       = "$SimBase\psx_net_efb\PSX.NET.EFB-2.0.0.2-2025-11-12-2"

#  Where the EFB config file is located (the EFB controls this and
#  expect the file to be in this location, so don't override this)
$PsxNetEfbConfigDir = "$env:USERPROFILE\Documents\PSX.NET.EFB"

# Location of PSX.NET.WeatherRadar and SimObjectRouter
$PsxNetWeatherRadarDir = "$SimBase\psx_net_weather_radar"
$SimObjectRouterDir    = "$SimBase\sim_object_router"

# Where the ACARS Print app is installed
$AcarsPrintDir      = "$SimBase\acars_print\AcarsPrintV1_1"

# Flavor-derived variables — overridden at runtime by psxhacks-current-flavor.ps1.
# These defaults apply when choose_flavors.ps1 has not yet been run.
$AirlineIcao    = "BAW"
$AirlineIata    = "BA"
$SimfestEmail   = ""
$PsxSoundsRb211 = "66"
$VpilotPlugin   = "Pushover"

# Your Hoppie logon code. Set this in the override file:
#   $HoppieLogonCode = "yourcode"
# If you have multiple codes and want to choose between them at startup,
# define a named hashtable instead and choose_flavors.ps1 will let you
# pick by name:
#   $HoppieLogonCodes = @{ "normal" = "yourcode1"; "testing" = "yourcode2" }
$HoppieLogonCode = "DUMMYLOGONCODE"

# Your Simfest Portal email address. Set this in the override file:
#   $SimfestEmail = "you@example.com"
# If you have multiple addresses and want to choose between them at startup,
# define a named hashtable instead and choose_flavors.ps1 will let you
# pick by name:
#   $SimfestEmails = @{ "work" = "work@example.com"; "personal" = "me@gmail.com" }

$FrankenusbDir      = "$SimBase\frankenusb"

# Options for the routers
$FrankenrouterDir           = "$SimBase\frankenrouter"
$FrankenrouterMasterOptions = @("--config-file=frankensim-core.toml")
$FrankenrouterSlaveOptions  = @("--config-file=frankensim-client.toml")
# Location of router web interface
$FrankenrouterSlaveWeb      = "http://localhost:8747"

# Options for the rest of the frankenaddons, e.g a config file name
#
# If port 10748 is used it is because those usually run in the master
# sim, and my master sim is on port 10748
#
# $ExampleOptions = @("--foo", "--bar=123")
$FrankenfreezeOptions = @()
$FrankentankerOptions = @()
$FrankenusbOptions  = @()
$FrankenwindOptions  = @()
$FrankenturbOptions = @()
$FrankenidentOptions = @()
$FrankenutilOptions = @()
$FrankencduproxyOptions = @()

# Which of the addons that we can manage you actually want started in
# your sim. You can override these in the override file.

$StartFrankenfreeze = $false
$StartFrankentanker = $false
$StartFrankenusb    = $false
$StartFrankenwind   = $false
$StartFrankenturb   = $false
$StartFrankenident  = $false
$StartFrankenutil   = $false

# Master-only addons
$StartBacars        = $true
$StartPsxNet        = $true

# Other addons
$StartCpdlc         = $false
$StartPsxSounds     = $false
$StartVpilot        = $false
$StartAcarsPrint    = $false
$StartEfb           = $false

# CDU
$StartFrankencduproxy = $false
$StartCsCdu           = $false

# Slave-only addons
$StartPsxNetMsfsRouter   = $true
$StartPsxNetWeatherRadar = $false
$StartSimObjectRouter    = $false
$CsCduExe = "$SimBase\hw\cs_cdu\CockpitSimulator v2025.2.7.exe"

# Set to $true in the override file to enable apply_window_positions.ps1
$ChangeWindowPositions = $false

# Retry interval and timeout (seconds) used by apply_window_positions.ps1 when
# waiting for an addon window to appear after the addon is started.
$WindowPositionSleepSeconds    = 0.5
$WindowPositionSleepSecondsMax = 30

# Human-readable display names for each sim addon key used in window-positioning scripts
$SimAddonNames = [ordered]@{
    "BACARS"               = "BACARS"
    "PSX.NET.MSFS"         = "PSX.NET MSFS Client"
    "PSX.NET.MSFS.Router"  = "PSX.NET MSFS Router"
    "PSX.NET"              = "PSX.NET"
    "PSXSounds"            = "PSX Sounds"
    "HAFAP/CPDLC"          = "HAFAP/CPDLC"
    "vPilot"               = "vPilot"
    "PSX.NET.EFB"          = "PSX.NET EFB"
    "ACARS Print App"      = "ACARS Print App"
    "frankenusb"           = "FrankenUSB"
    "frankenfreeze"        = "FrankenFreeze"
    "frankentanker"        = "FrankenTanker"
    "frankenwind"          = "FrankenWind"
    "frankenturb"          = "FrankenTurb"
    "frankenident"         = "FrankenIDENT"
    "frankenutil"          = "FrankenUtil"
    "frankencduproxy"      = "FrankenCDU Proxy"
    "frankenrouter slave"    = "FrankenRouter (slave)"
    "frankenrouter master"   = "FrankenRouter (master)"
    "PSX.NET.WeatherRadar"   = "PSX.NET WeatherRadar"
    "SimObjectRouter"        = "SimObjectRouter"
}


#
# Shared functions below
#


# Silently stop a process by name; does nothing if the process is not running
function KillProcess([string]$name) {
    Stop-Process -Name $name -Force -ErrorAction SilentlyContinue
}

# Apps launched as-is during sim startup (no custom start script
# needed).  Override $NonscriptedApps in the override file to replace
# this list entirely.
$NonscriptedApps = @()

function KillPythonScript([string]$scriptName) {
    Get-CimInstance Win32_Process -Filter "name LIKE 'python%.exe'" |
        Where-Object { $_.CommandLine -and $_.CommandLine -like "*$scriptName*" } |
        ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
}

function KillJavaJar([string]$jarName) {
    Get-CimInstance Win32_Process -Filter "name = 'java.exe'" |
        Where-Object { $_.CommandLine -like "*$jarName*" } |
        ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
}

function Delay([int]$seconds) {
    Write-Output "Waiting $seconds seconds..."
    Start-Sleep -Seconds $seconds
}

function start_nonscripted_apps {
    foreach ($app in $NonscriptedApps) {
        Write-Output "Starting $app..."
        Start-Process $app
    }
}

if (Test-Path $OverrideFile) { . $OverrideFile }

# Flavor settings override both defaults and machine-specific overrides.
if (Test-Path $FlavorFile) { . $FlavorFile }
